### ISSUE TITLE
duplicate symbol __channel : error when using pollfish with firebase_admob

### ISSUE THREAD

**Issue by SachinGanesh** [pollfish/flutter-plugin-pollfish#1]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    duplicate symbol __channel in:
        /app_location/build/ios/Debug-iphonesimulator/firebase_admob/libfirebase_admob.a(FLTMobileAd.o)
        /app_location/build/ios/Debug-iphonesimulator/flutter_pollfish/libflutter_pollfish.a(FlutterPollfishPlugin.o)
    ld: 1 duplicate symbol for architecture x86_64

**Comment by SachinGanesh** [comment]
Similar to [https://github.com/luanpotter/audioplayers/issues/34](https://github.com/luanpotter/audioplayers/issues/34)

**Comment by SachinGanesh** [comment]
This pull request fixes the issue: https://github.com/pollfish/flutter-plugin-pollfish/pull/2

**Comment by vourkosa** [comment]
thanks for bringing this up @SachinGanesh
