### ISSUE TITLE
"Uncaught ReferenceError: Pollfish is not defined"

### ISSUE THREAD

**Issue by sageata** [pollfish/flutter-plugin-pollfish#11]
I get the message bellow every now and then if the app goes in the background.

**I/chromium(30840): [INFO:CONSOLE(1)] "Uncaught ReferenceError: Pollfish is not defined", source:  (1)**

This is on an Android Simulator, Pixel 4, with Android 30.

I'm not sure what it means, but I hope is nothing that breaks the package.

**Comment by kaspanvo** [comment]
This is a harmless warning.
