### ISSUE TITLE
Pollfish plugin crashes in Version 2.0

### ISSUE THREAD

**Issue by niklasstttnr** [pollfish/flutter-plugin-pollfish#14]
We found a bug within the new version (2.0^) that the flutter plugin resets when the phone is in standby mode during a survey. I think it would be nice if you can take a short break during the survey, because it worked in the old version. But now the survey is just gone after going back in. Also, the plugin crashes when you tab out of the app and tab back in while pollfish is active. (e.g. You are in the middle of a survey and you get a message on WhatsApp you have to answer, then you leave the app and come back and the survey is gone and the plugin has to be reinitialized to work again). The plugin crashes in every state of activity, so during initialization, when it is already initialized or if you have the offer wall open.

Also if you leave the app with the back button and you go in and want to reinitialize it, it doesn't work anymore and you have to destroy the app that it's possible to initialize the plugin again.

In the older SDK version (1.*) of pollfish both cases don't happen.

**Comment by fotism23** [comment]
Hello, @niklasstttnr 

Thanks for the report.

We have just released version 2.0.4 which solves the issue you reported.
