### ISSUE TITLE
How to disable pollfish at certain points

### ISSUE THREAD

**Issue by geekydiamond** [pollfish/flutter-plugin-pollfish#4]
In our app a user earns points for an account. A user may have several accounts. When a poll is completed points are assigned to the correct account.
Two questions
1) I am currently calling 'init' whenever an account is selected so that I can set the requestUUID to the correct account. Is this acceptable to call init multiple times?
2) If a user logs out I don't want any surveys to show. Is there a way to disable pollfish until init is called again on login?

Btw, plugin was really easy to integrate, nice work!

**Comment by geekydiamond** [comment]
Second point I've solved because I have put the plugin into reward mode.
However, now have an additional question - once a survey is completed no further surveys are showing (even in test mode). This may be because there just aren't any surveys available, but just want to confirm that init does not need to be called again after a survey is completed.

**Comment by vourkosa** [comment]
reward mode hides Pollfish survey panel. You can show it with Pollfish show function whenever you want to show it (when a button is pressed for example). You can listen if a survey was received through the relevant notifications (please see the example in code).

If you are not using the Offerwall and you are using the single survey approach (Rewarded Survey) you are requesting a new survey every time you call init. If a survey gets completed or user gets screened out then no surveys will be received until a new request is made. Hope that helps.
