### ISSUE TITLE
In release mode "Survey Not Available notification" is not working

### ISSUE THREAD

**Issue by opensourcegps** [pollfish/flutter-plugin-pollfish#5]
After switching to release mode, onPollfishSurveyNotAvailable listener is not working. It was working in debug mode.

```
 FlutterPollfish.instance.init(
              apiKey: _api_key,
              pollfishPosition: 5,
              indPadding: 40,
              rewardMode: true,
              releaseMode: true,
              requestUUID: _unique_id_public,  
              offerwallMode:true);
```
```
FlutterPollfish.instance.setPollfishSurveyNotAvailableSurveyListener(onPollfishSurveyNotAvailable);
```
```
void onPollfishSurveyNotAvailable() => setState(() {

   debugPrint('survey not available');  //this one never called in release mode but works in debug mode.

  });
```

Other callbacks are working properly.

**Comment by kaspanvo** [comment]
hello @opensourcegps we have tested both on Android and iOS and onPollfishSurveyNotAvailable fires in both release and debug mode when no surveys are available. We used to the example app and logs also are visible on the screen

**Comment by opensourcegps** [comment]
@kaspanvo very strange. For me I only see this in logs:
```
D/FlutterPollfishPlugin(16193): onPollfishSurveyNotAvailable
```
but actual flutter function is not executed.

**Comment by kaspanvo** [comment]
@opensourcegps  when you run the example project, do you see in the app the logs on the screen when no survey is availalble?

**Comment by opensourcegps** [comment]
I have not tested with example project. However everything was working in debug mode. Only after switching to production, this problem appeared. Also I'm using:
```
rewardMode: true,
offerwallMode:true
```

**Comment by kaspanvo** [comment]
can you please test the example project in the offerwall mode tab and confirm that you do not see the logs?

**Comment by kaspanvo** [comment]
In debug mode it is not expected to get survey not available callback since there is always a test survey to test. Survey not available fires only after the initial initialization call

**Comment by opensourcegps** [comment]
I was receiving onPollfishSurveyNotAvailable in debug mode once in a while. Maybe once in 20 inits. I thought this was intentional to test "not available" option. I'll test with the example app.

**Comment by opensourcegps** [comment]
I've tested with example app. Problem is still there, only for Offerwall. Here is how to reproduce:

1. Set bool _releaseMode = true; 
2. Run example app. 
3. Switch to Offerwall tab.

Screen is stuck forever like this:
![Screenshot_1584029408](https://user-images.githubusercontent.com/7678445/76541759-569fdf00-6484-11ea-97bd-906d4b95da65.png)

In logs:
```
D/FlutterPollfishPlugin(16077): onPollfishSurveyNotAvailable
```

**Comment by kaspanvo** [comment]
Thanks for sharing that. I believe the issue is resolved. Please check v1.0.1

**Comment by opensourcegps** [comment]
works now, thanks!
