### ISSUE TITLE
Important Addition

### ISSUE THREAD

**Issue by Ola4606** [pollfish/flutter-plugin-pollfish#9]
Hello. I am trying to verify if a survey is going to get paid for by pollfish because I need to confirm this before rewarding users. But while talking with pollfish customer support they said the only 100% way to verify whether a survey is going to be paid for is by using a server to server callback. And I use firebase and I dont know how to do this. Is it possible if the plugin could help us with this. If we pass in the reqeust uuid somewhere?.. Please help... Thanks.. Love your plugin

**Comment by Ola4606** [comment]
@kaspanvo  @weakwire   @SachinGanesh   please check that issuse out.. People need to be able to confirm if a survey is not disapproved even if the user is eligible.. Thanks.. Please help out

**Comment by kaspanvo** [comment]
@Ola4606 the Flutter plugin notifies when a survey is completed or screened out locally with the local notifications. With those notifications you can adjust your UI but also if you want to reward your users. However the process (used in advertising also) is for responses to get validated on the server side and then notify the publisher's server side on the outcome. This is how the system works at the moment

**Comment by Ola4606** [comment]
@kaspanvo thanks for replying....

""  the Flutter plugin notifies when a survey is completed or screened out locally with the local notifications. With those notifications you can adjust your UI but also if you want to reward your users  ""

I am aware that the flutter plugin notifies me locally I just have question about this please.. Is this local notification always going to be 100 percent valid. I mean I hope pollfish would not eventually cancel the payment.. 



""  However the process (used in advertising also) is for responses to get validated on the server side and then notify the publisher's server side on the outcome. "" ------- Are you saying that it is not necessary then to do server to server callbacks.. You are sure the local one is valid?

**Comment by kaspanvo** [comment]
hello @Ola4606 as mentioned again the only way to be 100% guaranteed that a survey complete is valid, is by implementing s2s callbacks as described here https://www.pollfish.com/docs/s2s. You can skip that step if you do not have or do not want to implement a server side for your app but there is a risk involved (that a completed will be marked as fraud) and unfortunately this is how the system works at the moment.

**Comment by Ola4606** [comment]
Please can you explain how to implement a server side thing.. i am using firebase

**Comment by kaspanvo** [comment]
@Ola4606 you can read our step by step documentation here https://www.pollfish.com/docs/s2s. Unfortunately we do not have a guide on how to implement server side logic in your app with firebase.
